Fix compile error due to inline function using local symbol (Fix #428)
IndySockets/Indy pull request #429
Opened 2022-08-26 01:04 UTC by iadcode

It turns out that `const` declared within a function counts as a "local symbol" for the purposes of inlining and fails the build.

2022-08-26 16:31 UTC, rlebeau commented
Sorry, I hadn't seen this pull request yet when I checked in my own fix for the issue.  I just removed the `inline` rather than changing the `const` into a `var`.

2022-08-26 16:33 UTC, rlebeau requested changes
Please resync with the latest master, and either re-submit or close this PR as needed.

2022-08-29 00:27 UTC, iadcode commented
Hi @rlebeau, I've resynced with latest master and renamed the commit/PR appropriately.

2022-08-29 16:21 UTC, rlebeau commented
Rather than using a local `var`, if the `const` were moved outside of the function, would that allow the function to be inlined?

2022-08-31 00:07 UTC, Cirras commented
> error E2441: Inline function declared in interface section must not use local symbol 'a'

Afraid not, extracting the const gives the same error as before.

2022-08-31 00:09 UTC, iadcode commented
> error E2441: Inline function declared in interface section must not use local symbol 'a'

Afraid not, extracting the const gives the same error as before.

2022-08-31 05:32 UTC, PatrickvL commented
Would passing in `PAnsiChar('a'#0)` as an argument do the trick as well? That way no `a` variable is needed at all.

2022-09-02 00:27 UTC, iadcode commented
> Would passing in `PAnsiChar('a'#0)` as an argument do the trick as well? That way no `a` variable is needed at all.

`PAnsiChar(String('a'))` would probably work similarly, but I haven't checked.
I opted for the very explicit array of `PAnsiChar` because it seemed a sure thing that it would work consistently across different compilers/versions. After all, the original bug was basically a portability issue between Delphi compiler versions.

2022-09-02 19:59 UTC, rlebeau commented
> `PAnsiChar(String('a'))` would probably work similarly, but I haven't checked.

It would have to be `PAnsiChar(AnsiString('a'))` instead, if `PAnsiChar('a'#0)` does not work.

2022-09-05 00:51 UTC, Cirras commented
> > `PAnsiChar(String('a'))` would probably work similarly, but I haven't checked.
> 
> It would have to be `PAnsiChar(AnsiString('a'))` instead, if `PAnsiChar('a'#0)` does not work.

Since Indy supports all of these different compilers and compiler versions, I would expect the behavior here to be informed by the type mappings.

- `PIdAnsiChar` sometimes aliasesto `PAnsiChar` sometimes to `PByte`, and sometimes to `MarshaledAString`.
- There's no `TIdAnsiString` alias.

Would there be any consistent way to do the equivalent of `PAnsiChar(AnsiString('a'))`, or even `PAnsiChar('a'#0)`, then?

2022-09-05 00:52 UTC, iadcode commented
> > `PAnsiChar(String('a'))` would probably work similarly, but I haven't checked.
> 
> It would have to be `PAnsiChar(AnsiString('a'))` instead, if `PAnsiChar('a'#0)` does not work.

Since Indy supports all of these different compilers and compiler versions, I would expect the behavior here to be informed by the type mappings.

- `PIdAnsiChar` sometimes aliasesto `PAnsiChar` sometimes to `PByte`, and sometimes to `MarshaledAString`.
- There's no `TIdAnsiString` alias.

Would there be any consistent way to do the equivalent of `PAnsiChar(AnsiString('a'))`, or even `PAnsiChar('a'#0)`, then?

2022-09-07 16:25 UTC, rlebeau commented
> Would there be any consistent way to do the equivalent of `PAnsiChar(AnsiString('a'))`, or even `PAnsiChar('a'#0)`, then?

Not cleanly, it would probably end up looking something like this:

```
{$IFDEF USE_MARSHALLED_PTRS}
var
  M: TMarshaller;
{$ENDIF}
...
Result := BIO_ctrl(b, BIO_C_SET_ACCEPT, 1,
  {$IFDEF USE_MARSHALLED_PTRS}
  M.AsAnsi('a').ToPointer
  {$ELSE}
    PAnsiChar(
      {$IFDEF STRING_IS_ANSI}
      'a'#0
      {$ELSE}
      AnsiString('a')
      {$ENDIF}
    )
  {$ENDIF}
);
```

2022-09-09 16:08 UTC, rlebeau approved these changes

2022-09-09 16:08 UTC, merged